### ISSUE TITLE
DLL version

### ISSUE THREAD

**Issue by caporalesimone** [broker0/path_server#1]
Could be possible to convert the executable into a DLL in order to integrate it as a plugin of RazorEnhanced?

The idea is to integrate the binary and load it at the startup of RE, then provide all the APIs to the python scripters.

**Comment by broker0** [comment]
I think that it is possible to build the project as a dll. But this will require certain improvements, in particular, turning off the graphical world browser.
Potentially, it could look like this - RE loads the dll and calls a certain initialization function, and then deinitializes it in the same way, before unloading

**Comment by caporalesimone** [comment]
Yes the idea is like you say.
Let me know if you are interested in this.
Feel free to write me in discord
SimonSoft#6247

**Comment by broker0** [comment]
In commit 6e16135 the ability to build the project as a standalone dll was added
